name: "Vprofile IAC"

on: 
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

jobs:
  terraform:
    name: "Apply Terraform Code Changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    env:
      # Credenciais para implantação na AWS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Corrigido o nome da variável
      # S3 bucket para armazenar o estado do Terraform
      BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
      AWS_REGION: us-east-1
      EKS_CLUSTER: vprofile-eks

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4  # Corrigido nome da action

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v4
        # with:
        #   terraform_version: 1.6.3 -- para comit

      - name: Initialize Terraform
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Check Terraform Formatting
        id: fmt 
        run: terraform fmt -check

      - name: Validate Terraform Configuration
        id: validate
        run: terraform validate

      - name: Generate Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: Check Terraform Plan Status 
        if: steps.plan.outcome == 'failure'
        run: exit 1
